### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by mldulaney** [moshen/gotermimg#1]
go get fails:

go get github.com/moshen/gotermimg/
package github.com/moshen/gotermimg
        imports github.com/moshen/gotermimg/vendor/gif: must be imported as gif
package github.com/moshen/gotermimg
        imports github.com/moshen/gotermimg/vendor/resize: must be imported as resize

**Comment by moshen** [comment]
Sorry!  I haven't gotten around to update this for Go 1.6 :(
